# .github/workflows/chromatic.yml

# Name of the workflow
name: 'Chromatic'

# Run on every push to the repository
on: push

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for Chromatic to correctly identify base commits

      - name: Install dependencies
        run: npm install

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true # Optional: Prevents the workflow from failing on visual changes